### ISSUE TITLE
Cannot play additional songs

### ISSUE THREAD

**Issue by JapanYoshi** [hmxmilohax/rock-band-blitz-deluxe#7]
Windows 10, playing on RPCS3. Can successfully boot into Rock Band Blitz Deluxe, except that it's still the trial version.

I installed one of the song packs, and the songs included show up in Rock Band Blitz Deluxe. However, they are grayed out and not selectable, and the game asks me to "unlock full game", despite the fact that the .pkg file for unlocking the full Rock Band Blitz game is--to my knowledge--correctly installed on RPCS3.

Can anyone help with this? Do I have to unlock the full game while the game is still unpatched, THEN patch the game with Rock Band Blitz Delxue?

**Comment by jnackmclain** [comment]
You are missing the raps and edat for the game which blitz dx does not provide
